/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ahyaghifari.aplikasiresepmasakan;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import model.ResepMasakan;

/**
 *
 * @author Ahya Ghifari
 */
public class FrameTambahResepMasakan extends javax.swing.JFrame {

    int status = 0; // inisialisasi status agar frame mengetahui sedang digunakan untuk menambah atau mengedit resep masakan
    
    /**
     * Creates new form FrameTambahResepMasakan
     */
    
    // method untuk mengenerate id reseo secara otomatis
   public String makeIdResepMasakan(){
       ResepMasakan lastResep = FrameAplikasiResepMasakan.resepResepMasakan.get(FrameAplikasiResepMasakan.resepResepMasakan.size() - 1); // mengambil elemen resep pada index terakhir dari array list resep
       String lastIndex = lastResep.getIdResepMasakan(); // mengambil id dari element resep yang terakhir
       String lastId  = lastIndex.substring(3); // mengambil angka pertama sampai seterusnya dari resep
       int id = Integer.parseInt(lastId) + 1;  // menambahkan 1 angka pada id terakhir sehingga increment
       return "RSP" + String.valueOf(id); // mengembalikan id yang sudah ditambahkan
   }
    
    // konstruktor pertama, digunakan ketika ingin menambah resep
    public FrameTambahResepMasakan() {
        initComponents();
        setLocationRelativeTo(null);
        
        // mengubah tulisan pada desain form menjadi ubah
        tfIdResep.setText(makeIdResepMasakan());
        lblTitle.setText("Tambah Resep Masakan");
        btnSimpan.setText("Tambah");
        tfNamaMasakan.requestFocus();
        status = 0;
    }

   // konstruktor kedua, digunakan ketika ingin mengedit resep
   public FrameTambahResepMasakan(ResepMasakan resepMasakan){
       initComponents();
       setLocationRelativeTo(null);
       
       // mengubah tulisan pada desain form menjadi ubah
       lblTitle.setText("Ubah Resep Masakan");
       btnSimpan.setText("Ubah");
       tfNamaMasakan.requestFocus();
       
       // mengisi form sesuai resep yang dipilih
       tfIdResep.setText(String.valueOf( resepMasakan.getIdResepMasakan()));
       tfNamaMasakan.setText(resepMasakan.getNama());
       tfLamaMemasak.setText(String.valueOf(resepMasakan.getLamaMemasak()));
       taBahanBahan.setText(resepMasakan.getBahanBahan());
       taCaraMemasak.setText(resepMasakan.getCaraMemasak());
       status = 1;
   }
   
   // method untuk clear form
   public void resetForm(){
        tfNamaMasakan.setText("");
        tfLamaMemasak.setText("");
        taBahanBahan.setText("");
        taCaraMemasak.setText("");
   }
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        btnKembali = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        tfIdResep = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        tfNamaMasakan = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        tfLamaMemasak = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        taBahanBahan = new javax.swing.JTextArea();
        jPanel7 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        taCaraMemasak = new javax.swing.JTextArea();
        btnSimpan = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(222, 160, 87));

        lblTitle.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(252, 255, 231));
        lblTitle.setText("Tambah Resep Masakan");

        btnKembali.setBackground(new java.awt.Color(222, 160, 87));
        btnKembali.setForeground(new java.awt.Color(255, 255, 255));
        btnKembali.setText("Kembali");
        btnKembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKembaliActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 275, Short.MAX_VALUE)
                .addComponent(btnKembali)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTitle)
                    .addComponent(btnKembali))
                .addGap(15, 15, 15))
        );

        jPanel1.add(jPanel2);
        jPanel2.setBounds(10, 10, 530, 50);

        jPanel3.setBackground(new java.awt.Color(252, 255, 231));

        jLabel2.setText("Id Resep");

        tfIdResep.setEditable(false);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(tfIdResep, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tfIdResep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel3);
        jPanel3.setBounds(10, 80, 230, 34);

        jPanel4.setBackground(new java.awt.Color(252, 255, 231));

        jLabel3.setText("Nama Masakan");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(tfNamaMasakan, javax.swing.GroupLayout.DEFAULT_SIZE, 269, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tfNamaMasakan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel4);
        jPanel4.setBounds(10, 130, 380, 34);

        jPanel5.setBackground(new java.awt.Color(252, 255, 231));

        jLabel4.setText("Lama Memasak");

        tfLamaMemasak.setMinimumSize(new java.awt.Dimension(64, 40));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(tfLamaMemasak, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tfLamaMemasak, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel5);
        jPanel5.setBounds(10, 180, 280, 34);

        jPanel6.setBackground(new java.awt.Color(252, 255, 231));

        jLabel5.setText("Bahan - Bahan");

        taBahanBahan.setColumns(20);
        taBahanBahan.setRows(5);
        jScrollPane1.setViewportView(taBahanBahan);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 518, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel6);
        jPanel6.setBounds(10, 230, 530, 120);

        jPanel7.setBackground(new java.awt.Color(252, 255, 231));

        jLabel6.setText("Cara Memasak");

        taCaraMemasak.setColumns(20);
        taCaraMemasak.setLineWrap(true);
        taCaraMemasak.setRows(5);
        jScrollPane2.setViewportView(taCaraMemasak);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 518, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel7);
        jPanel7.setBounds(10, 360, 530, 130);

        btnSimpan.setBackground(new java.awt.Color(206, 148, 97));
        btnSimpan.setForeground(new java.awt.Color(255, 255, 255));
        btnSimpan.setText("Tambah");
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });
        jPanel1.add(btnSimpan);
        btnSimpan.setBounds(20, 500, 120, 30);

        btnReset.setText("Reset");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });
        jPanel1.add(btnReset);
        btnReset.setBounds(428, 500, 90, 30);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 539, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed

        // mengambil nilai dari komponen komponen pada desain
        String idResep = tfIdResep.getText();
        String namaMasakan = tfNamaMasakan.getText();
        String lamaMemasak = tfLamaMemasak.getText();
        String bahanBahan = taBahanBahan.getText();
        String caraMemasak = taCaraMemasak.getText();
        
        // validasi form apakah sudah diisi atau belum
        if(namaMasakan.equals("") || lamaMemasak.equals("") || bahanBahan.equals("") || caraMemasak.equals("")){
        // jika masih ada yang belum diisi
        
            JOptionPane.showMessageDialog(this, "Input masih ada yang belum diisi", "INPUT", JOptionPane.ERROR_MESSAGE);
                
        // jika semua sudah terisi    
        }else{
            
        
        // TAMBAH : menambahkan resep makanan ketilka status 0 atau sedang tambah
        if(status == 0){ 
            FrameAplikasiResepMasakan.resepResepMasakan.add(new ResepMasakan(idResep, namaMasakan, lamaMemasak, bahanBahan, caraMemasak));
            JOptionPane.showMessageDialog(this, "Resep " + namaMasakan + " berhasil ditambahkan", "Resep Baru", JOptionPane.INFORMATION_MESSAGE);
        
        // EDIT : mengedit resep masakan ketika status sedang 1 atau sedang mengedit
        }else{
            
            int listIndex = 0; // inisialisasi index
            
            // // melakukan perulangan untuk mencari index yang cocok dari id pada array list dengan id text field id
            for(ResepMasakan rm: FrameAplikasiResepMasakan.resepResepMasakan){
                if(rm.getIdResepMasakan().equals(idResep)){
                    listIndex = FrameAplikasiResepMasakan.resepResepMasakan.indexOf(rm); // mengambil index
                    break;
                }
            }
            
            // membuat objek resep baru
            ResepMasakan updateResep = new ResepMasakan(tfIdResep.getText(), namaMasakan, lamaMemasak, bahanBahan, caraMemasak);
            
            // menimpa objek resep lama dengan objek resep yang baru sesuai index yang didapat
            FrameAplikasiResepMasakan.resepResepMasakan.set(listIndex, updateResep);
            
            // pesan informasi
            JOptionPane.showMessageDialog(this, "Resep " + namaMasakan + " berhasil diubah", "Update Resep", JOptionPane.INFORMATION_MESSAGE);
            
            // memanggil dan menampilkan frame detail dengan data yang sudah diubah
            FrameDetailResepMasakan detailFrame = new FrameDetailResepMasakan(updateResep);
            detailFrame.setVisible(true);
            
        }
        dispose();
        }
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void btnKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKembaliActionPerformed
        dispose();
    }//GEN-LAST:event_btnKembaliActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        if(status == 0){ // ketika sedang menambah
            resetForm();
        }else{ // ketika sedang mengubah
            int konfirmasi = JOptionPane.showConfirmDialog(this, "Yakin ingin mereset resep yang sudah ada", "Reset", JOptionPane.WARNING_MESSAGE);
            if(konfirmasi == 0){
                resetForm();
            }
        }
    }//GEN-LAST:event_btnResetActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameTambahResepMasakan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameTambahResepMasakan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameTambahResepMasakan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameTambahResepMasakan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameTambahResepMasakan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnKembali;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTextArea taBahanBahan;
    private javax.swing.JTextArea taCaraMemasak;
    private javax.swing.JTextField tfIdResep;
    private javax.swing.JTextField tfLamaMemasak;
    private javax.swing.JTextField tfNamaMasakan;
    // End of variables declaration//GEN-END:variables
}
