/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ahyaghifari.aplikasiresepmasakan;

import java.io.FileWriter;
import java.io.IOException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import model.ResepMasakan;

/**
 *
 * @author Ahya Ghifari
 */
public class FrameDetailResepMasakan extends javax.swing.JFrame {

    /**
     * Creates new form FrameDetailResepMasakan
     */
    
    ResepMasakan resepMasakan;
    
    public FrameDetailResepMasakan(){
        initComponents();
        setLocationRelativeTo(null);
    }
    
    public FrameDetailResepMasakan(ResepMasakan rm) {
        initComponents();
        setLocationRelativeTo(null);
        
        // melakukan beberapa setting terhadap design sesuai dengan resep masakan yang sudah diterima dari frame utama
        setTitle("Detail Resep : " + rm.getNama());
        resepMasakan = rm;
        lblNamaMasakan.setText(rm.getNama());
        lblLamaMemasak.setText(String.valueOf(rm.getLamaMemasak()));
        taBahanBahan.setText(rm.getBahanBahan());
        taCaraMemasak.setText(rm.getCaraMemasak());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnKembali = new javax.swing.JButton();
        lblNamaMasakan = new javax.swing.JLabel();
        lblLamaMemasak = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        taCaraMemasak = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        taBahanBahan = new javax.swing.JTextArea();
        btnEdit = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        btnCetak = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        btnKembali.setBackground(new java.awt.Color(252, 255, 231));
        btnKembali.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        btnKembali.setText("Kembali");
        btnKembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKembaliActionPerformed(evt);
            }
        });

        lblNamaMasakan.setFont(new java.awt.Font("Poppins SemiBold", 0, 25)); // NOI18N
        lblNamaMasakan.setForeground(new java.awt.Color(206, 148, 97));
        lblNamaMasakan.setText("Nasi Goreng");

        lblLamaMemasak.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        lblLamaMemasak.setForeground(new java.awt.Color(153, 153, 153));
        lblLamaMemasak.setText("30 menit");

        jLabel2.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 153, 153));
        jLabel2.setText("Lama Memasak : ");

        jLabel3.setFont(new java.awt.Font("Poppins Medium", 0, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(222, 160, 87));
        jLabel3.setText("Cara Memasak :");

        jLabel4.setFont(new java.awt.Font("Poppins Medium", 0, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(222, 160, 87));
        jLabel4.setText(" Bahan - Bahan : ");

        taCaraMemasak.setEditable(false);
        taCaraMemasak.setColumns(20);
        taCaraMemasak.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        taCaraMemasak.setLineWrap(true);
        taCaraMemasak.setRows(5);
        taCaraMemasak.setWrapStyleWord(true);
        taCaraMemasak.setAutoscrolls(false);
        taCaraMemasak.setSelectionColor(new java.awt.Color(222, 160, 87));
        jScrollPane3.setViewportView(taCaraMemasak);

        taBahanBahan.setEditable(false);
        taBahanBahan.setColumns(20);
        taBahanBahan.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        taBahanBahan.setLineWrap(true);
        taBahanBahan.setRows(5);
        taBahanBahan.setAutoscrolls(false);
        taBahanBahan.setSelectionColor(new java.awt.Color(222, 160, 87));
        jScrollPane4.setViewportView(taBahanBahan);

        btnEdit.setBackground(new java.awt.Color(222, 160, 87));
        btnEdit.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        btnEdit.setForeground(new java.awt.Color(255, 255, 255));
        btnEdit.setText("Edit");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        btnHapus.setBackground(new java.awt.Color(252, 255, 231));
        btnHapus.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        btnHapus.setForeground(new java.awt.Color(222, 160, 87));
        btnHapus.setText("Hapus");
        btnHapus.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(222, 160, 87), 1, true));
        btnHapus.setMinimumSize(new java.awt.Dimension(40, 25));
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });

        btnCetak.setBackground(new java.awt.Color(252, 255, 231));
        btnCetak.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        btnCetak.setForeground(new java.awt.Color(222, 160, 87));
        btnCetak.setText("Cetak");
        btnCetak.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(222, 160, 87), 1, true));
        btnCetak.setMinimumSize(new java.awt.Dimension(40, 25));
        btnCetak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCetakActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnCetak, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnKembali)
                        .addGap(16, 16, 16))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblLamaMemasak)))
                        .addContainerGap(31, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblNamaMasakan)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnEdit)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnKembali)
                    .addComponent(btnCetak, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNamaMasakan)
                    .addComponent(btnEdit)
                    .addComponent(btnHapus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLamaMemasak)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        
    }//GEN-LAST:event_formWindowClosed

    private void btnKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKembaliActionPerformed
        dispose();
    }//GEN-LAST:event_btnKembaliActionPerformed

    // event ketika tombol edit ditekan
    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        FrameTambahResepMasakan frameTambah = new FrameTambahResepMasakan(resepMasakan);
        frameTambah.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnEditActionPerformed

    // event ketika tombol hapus ditekan
    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        // konfirmasi apakah pengguna ingin menghapus resep yang dipilih atau tidak
        int konfirmasi = JOptionPane.showConfirmDialog(this, "Yakin ingin menghapus " + resepMasakan.getNama(), "Hapus Resep",  JOptionPane.YES_NO_OPTION);
        if(konfirmasi == 0){
            
            int resepIndex = 0; // inisialisasi index
            
            // melakukan perulangan untuk mencari index yang cocok dari id pada array list dengan id pada detail resep
            for(ResepMasakan rm : FrameAplikasiResepMasakan.resepResepMasakan){
                if(rm.getIdResepMasakan() == resepMasakan.getIdResepMasakan()){
                    resepIndex = FrameAplikasiResepMasakan.resepResepMasakan.indexOf(rm); // mengambil index
                    break;
                }
            }
            FrameAplikasiResepMasakan.resepResepMasakan.remove(resepIndex); // menghapus elemnt resep pada array list resep masakan dengan index yang sesuai
            dispose();
        }
    }//GEN-LAST:event_btnHapusActionPerformed

    private void btnCetakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCetakActionPerformed
        // pilih destinasi simpan file 
        JFileChooser selectDestination = new JFileChooser();
        selectDestination.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        selectDestination.showSaveDialog(this);
        String path = selectDestination.getSelectedFile().getAbsolutePath();
        
        // mengambil tanggal dan waktu        
        Date now = new Date();
        SimpleDateFormat dateFormat = new SimpleDateFormat("dd-mm-yyyy hh:mm:ss");
        String strDate = dateFormat.format(now);
        
        System.out.println(path + "\\Resep " + resepMasakan.getNama() + " - By Mamamia.txt");
        try {
            
            FileWriter fileResep = new FileWriter(path + "\\Resep " + resepMasakan.getNama() + " - By Mamamia.txt"); // buat file
            fileResep.write("Resep Masakan " + resepMasakan.getNama() + "\n");
            fileResep.write("By Mamamia / " + strDate + "\n\n");
            fileResep.write("Lama Memasak : " + resepMasakan.getLamaMemasak() + "\n\n");
            fileResep.write("Bahan - Bahan :\n");
            fileResep.write(resepMasakan.getBahanBahan() + "\n\n");
            fileResep.write("Cara Memasak : \n");
            fileResep.write(resepMasakan.getCaraMemasak() + "\n\n");
            fileResep.write("Resep by Mamamia");
            fileResep.close();
            
            // pesan konfirmasi
            JOptionPane.showMessageDialog(this, "File berhasil disimpan", "Cetak", JOptionPane.INFORMATION_MESSAGE);
            
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this, "File tidak berhasil disimpan", "Cetak", JOptionPane.ERROR_MESSAGE);
            Logger.getLogger(FrameDetailResepMasakan.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnCetakActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameDetailResepMasakan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameDetailResepMasakan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameDetailResepMasakan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameDetailResepMasakan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameDetailResepMasakan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCetak;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnKembali;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel lblLamaMemasak;
    private javax.swing.JLabel lblNamaMasakan;
    private javax.swing.JTextArea taBahanBahan;
    private javax.swing.JTextArea taCaraMemasak;
    // End of variables declaration//GEN-END:variables
}
